### ISSUE TITLE
Mautic prefix is hardcoded

### ISSUE THREAD

**Issue by robwent** [kuzmany/mautic-mail-tester-bundle#1]
Currently, if you change the username in the plugin settings, you still get sent to the micropayment screen as the url has the mautic prefix added here:

https://github.com/kuzmany/mautic-mail-tester-bundle/blob/master/Controller/MailTesterController.php#L42

I just tested by changing that to the username that I signed up with and the links then worked.

I'm not sure how to get the setting info to send a pull request though.

**Comment by kuzmany** [comment]
Yes, you're right. Get back forgotten code and now works properly.
